// scripts/enable_conductor.js
// Generated by Yennefer Orchestrator V2 - Swarm Consensus
require("dotenv").config();
const hre = require("hardhat");

async function main() {
  const CONTRACT_ADDRESS = "0x542db00D9c83F4444cAD5353D1580D97baFaBb50";

  console.log("⚡ Yennefer: Initializing Genesis Conductor on Base Mainnet...");
  
  // 1. Get Signer (Your Wallet)
  const [deployer] = await hre.ethers.getSigners();
  console.log(`🔑 Operator: ${deployer.address}`);

  // 2. Attach to Contract
  const Genesis = await hre.ethers.getContractFactory("Genesis");
  const conductor = Genesis.attach(CONTRACT_ADDRESS);

  // 3. Verify ownership
  const owner = await conductor.owner();
  console.log(`👤 Contract Owner: ${owner}`);
  
  if (owner.toLowerCase() !== deployer.address.toLowerCase()) {
    throw new Error("FATAL: Deployer is not contract owner!");
  }

  // 4. Check if already active
  const isActive = await conductor.conductorActive();
  if (isActive) {
    console.log("ℹ️  Conductor is already active.");
    return;
  }

  // 5. Execute State Change (The "Big Red Button")
  console.log("🚀 Sending 'startConductor()' transaction...");
  const tx = await conductor.startConductor({ gasLimit: 200000 });
  
  console.log(`⏳ Pending: ${tx.hash}`);
  const receipt = await tx.wait();

  console.log("✅ GENESIS CONDUCTOR IS ONLINE.");
  console.log(`🔗 https://basescan.org/tx/${tx.hash}`);
  console.log(`📦 Block: ${receipt.blockNumber}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
